name: Create Approval Issue

on:
  push:
    branches:
      - dev
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  create-approval-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Create Approval Issue
        uses: actions/github-script@v6
        with:
          script: |
            // Get the correct SHA based on the event type
            let commitSha = '';
            if (context.eventName === 'pull_request') {
              commitSha = context.payload.pull_request.merge_commit_sha;
            } else {
              commitSha = context.sha;
            }
            
            const shortSha = commitSha.substring(0, 7);
            
            const issueBody = `
            Please review and approve the deployment to staging.
            
            To approve, comment with one of these keywords: "approve", "LGTM"
            
            --- 
            Metadata (do not modify):
            \`\`\`json
            {
              "commit_sha": "${commitSha}",
              "branch": "dev",
              "triggered_by": "${context.eventName}"
            }
            \`\`\`
            `;
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Deploy to Staging needs approval - ${shortSha}`,
              body: issueBody,
              labels: ['deployment-approval']
            });
            console.log(`Created issue #${issue.data.number}`);
